### ISSUE TITLE
Allow custom (shorter) timeouts

### ISSUE THREAD

**Issue by MCOfficer** [lagged/apt-spy2#42]
I recently [recommended](https://github.com/actions/virtual-environments/issues/675#issuecomment-609780588) apt-spy2 for CI environments, to ensure `apt-get install` does not fail, ever. The usecase is just to find a *working* mirror, quickly.

Trying it out, i noticed that `apt-spy2 check` stalls for about 2 minutes because a single mirror in the list is unreachable. Some of our CI runs complete in less time, so it would be cool if one could speed up `apt-spy2 check`. In my opinion, the best way to do so would be a custom timeout - set it to 3s and you get a working mirror almost immediately.

Edit: this probably applies to all other subcommands as well.

**Comment by till** [comment]
@MCOfficer let me know if you want to start a PR, happy to help.

**Comment by MCOfficer** [comment]
> @MCOfficer let me know if you want to start a PR, happy to help.

I'm not familiar with ruby and don't have time to get into it, sorry. Here's hoping someone else picks it up.

**Comment by till** [comment]
@MCOfficer Could be as simple as this: https://stackoverflow.com/a/26066923 (in the downloader class).
