### ISSUE TITLE
`can't modify frozen String` error

### ISSUE THREAD

**Issue by parthshyara** [lagged/apt-spy2#92]
The comment `# frozen_string_literal: true` was added in a [recent commit](https://github.com/lagged/apt-spy2/pull/83/commits/a10730304895d7e0706c09b57794cf857da5e7f5) that leads to the following error in the CI.

`can't modify frozen String: "## Updated on 2023-02-13 07:47:24 +0000 by apt-spy2\n"`

#91 fixes the issue.

**Comment by parthshyara** [comment]
@till Please review this. We are still unable to use this tool in the CI because of the mentioned issue.

**Comment by till** [comment]
Thanks again!
